version: "3"

services:
  momca:
    image: momca
    build:
      context: ./config
      dockerfile: ./Dockerfile
      args:
        BACKUP_TRIGGER: ${BACKUP_TRIGGER:-0 0 4 * * ?}
        BRANCH: ${BRANCH:-master}
        CACHE_SIZE: ${CACHE_SIZE:-256}
        COLLECTION_CACHE: ${COLLECTION_CACHE:-256}
        HTTPS_PORT: ${HTTPS_PORT:-8443}
        HTTP_PORT: ${HTTP_PORT:-8080}
        INIT_MEMORY: ${INIT_MEMORY:-256}
        LUCENE_BUFFER: ${LUCENE_BUFFER:-256}
        MAIL_DOMAIN: ${MAIL_DOMAIN}
        MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_USER: ${MAIL_USER}
        MAX_MEMORY: ${MAX_MEMORY:-2048}
        PASSWORD: ${PASSWORD}
        REPOSITORY: ${REPOSITORY:-https://github.com/icaruseu/mom-ca.git}
        SERVER_NAME: ${SERVER_NAME:-localhost}
        SMTP_URL: ${SMTP_URL}
        USE_SSL: ${USE_SSL:-false}
    environment:
        HTTP_PORT: ${HTTP_PORT:-8080}
    volumes:
      - data:/opt/momca/mom.XRX-data
      - ./restore:/tmp/restore
      - ./backup:/opt/momca/mom.XRX-data/export
      - ./logs:/opt/momca/mom.XRX/localhost/webapp/WEB-INF/logs  
    container_name: momca
    restart: always
    networks:
      - default
    labels:
      - traefik.backend=momca-backend
      - traefik.docker.network=${TRAEFIK_NETWORK:-traefik}
      - traefik.frontend.rule=Host:${HOST}
      - traefik.enable=true
      - traefik.port=${HTTP_PORT:-8080}

volumes:
  data: {}

networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK:-traefik}
