version: "3"

services:
  momca-dev:
    image: momca:latest
    volumes:
      - ./backup:/opt/momca/mom.XRX-data/export
      - ./dev/data:/opt/momca/mom.XRX-data
      - ./dev/src:/opt/momca/mom.XRX
      - ./restore:/tmp/restore
    container_name: momca-dev
    restart: always
    healthcheck:
      disable: true
    ports:
      - ${HTTP_PORT:-8080}
      - ${HTTPS_PORT:-8443}
