version: "3"

services:
  momca-dev:
    image: momca:latest
    volumes:
      - ./backup:/opt/momca/mom.XRX-data/export
      - ./data:/opt/momca/mom.XRX-data
      - ./restore:/tmp/restore
      - ./src:/opt/momca/mom.XRX
    container_name: momca-dev
    restart: always
    ports:
      - ${HTTP_PORT:-8080}
      - ${HTTPS_PORT:-8443}
