version: "3"

services:
  momca-dev:
    image: momca:latest
    volumes:
      - ./backup:/opt/momca/mom.XRX-data/export
      - ./restore:/tmp/restore
      - data:/opt/momca/mom.XRX-data
      - src:/opt/momca/mom.XRX
    container_name: momca-dev
    restart: always
    ports:
      - ${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
      - ${HTTPS_PORT:-8443}:${HTTPS_PORT:-8443}
    healthcheck:
      disable: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${DEV_DATA_PATH}
      o: bind
  src:
    driver: local
    driver_opts:
      type: none
      device: ${DEV_SRC_PATH}
      o: bind
